apiVersion: v1
kind: Service
metadata:
  name: malware-detector-service
  labels:
    app: malware-detector
spec:
  type: LoadBalancer
  selector:
    app: malware-detector
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: monitoring
    protocol: TCP
    port: 9090
    targetPort: 9090
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: v1
kind: Service
metadata:
  name: malware-detector-nodeport
  labels:
    app: malware-detector
spec:
  type: NodePort
  selector:
    app: malware-detector
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
